In [30]:
import pandas as pd 
import matplotlib.pyplot as plt

In [31]:
df =pd.read_csv("BookDataTiki.csv")
df.head()

,id,sku,name,short_description,price,discount,all_time_quantity_sold,discount_rate,review_count,inventory_status
0,74021317,5977911599303,Cây Cam Ngọt Của Tôi,“Vị chua chát của cái nghèo hòa trộn với vị ng...,79100,28900,60433.0,27,12218,available
1,184466860,6027901073690,Hành Tinh Của Một Kẻ Nghĩ Nhiều,"“Đó là mùa hè năm 2020, mùa hè của COVID-19 và...",59500,26500,13281.0,31,1355,available
2,189643105,7150413107642,Không Phải Sói Nhưng Cũng Đừng Là Cừu -Tặng kè...,SÓI VÀ CỪU - BẠN KHÔNG TỐT NHƯ BẠN NGHĨ ĐÂU! L...,88500,39500,8716.0,31,1054,available
3,207841114,1646492661143,Ghi Chép Pháp Y – Những Cái Chết Bí Ẩn,GHI CHÉP PHÁP Y - NHỮNG CÁI CHẾT BÍ ẨN – Làm c...,105000,45000,3002.0,30,425,available
4,106863963,7417324116157,Tâm Lý Học - Phác Họa Chân Dung Kẻ Phạm Tội,TÂM LÝ HỌC TỘI PHẠM - PHÁC HỌA CHÂN DUNG KẺ PH...,101000,44000,20181.0,30,5916,available

In [32]:
_data = pd.DataFrame({
    'Unique':df.nunique(),
    'Null':df.isnull().sum(),
    'NullPercent':df.isnull().sum() / len(df),
    'Duplicated' :df.duplicated().sum(),
    'NaN':df.isna().sum(),
    'Type':df.dtypes.values
})
_data

                        Unique  Null  NullPercent  Duplicated  NaN     Type
id                         791     0       0.0000           8    0    int64
sku                        791     0       0.0000           8    0    int64
name                       791     0       0.0000           8    0   object
short_description          747     0       0.0000           8    0   object
price                      486     0       0.0000           8    0    int64
discount                   360     0       0.0000           8    0    int64
all_time_quantity_sold     685    18       0.0225           8   18  float64
discount_rate               57     0       0.0000           8    0    int64
review_count               477     0       0.0000           8    0    int64
inventory_status             1     0       0.0000           8    0   object

In [33]:
df.drop_duplicates()

,id,sku,name,short_description,price,discount,all_time_quantity_sold,discount_rate,review_count,inventory_status
0,74021317,5977911599303,Cây Cam Ngọt Của Tôi,“Vị chua chát của cái nghèo hòa trộn với vị ng...,79100,28900,60433.0,27,12218,available
1,184466860,6027901073690,Hành Tinh Của Một Kẻ Nghĩ Nhiều,"“Đó là mùa hè năm 2020, mùa hè của COVID-19 và...",59500,26500,13281.0,31,1355,available
2,189643105,7150413107642,Không Phải Sói Nhưng Cũng Đừng Là Cừu -Tặng kè...,SÓI VÀ CỪU - BẠN KHÔNG TỐT NHƯ BẠN NGHĨ ĐÂU! L...,88500,39500,8716.0,31,1054,available
3,207841114,1646492661143,Ghi Chép Pháp Y – Những Cái Chết Bí Ẩn,GHI CHÉP PHÁP Y - NHỮNG CÁI CHẾT BÍ ẨN – Làm c...,105000,45000,3002.0,30,425,available
4,106863963,7417324116157,Tâm Lý Học - Phác Họa Chân Dung Kẻ Phạm Tội,TÂM LÝ HỌC TỘI PHẠM - PHÁC HỌA CHÂN DUNG KẺ PH...,101000,44000,20181.0,30,5916,available
...,...,...,...,...,...,...,...,...,...,...
795,8965213,8389747336996,The Magic - Phép màu,"Trong suốt hơn 20 thế kỷ qua, những lời dạy tr...",158000,0,12257.0,0,966,available
796,160585834,5252334649041,Tôi Thích Tin Tức Tố Của Cậu - Tập 1 (Tặng Kèm...,"Ở trường học, Đoàn Gia Diễn coi Lộ Tinh Từ kẻ ...",113400,55600,412.0,33,154,available
797,984938,2422703672403,Gã Nghiện Giày - Tự Truyện Của Nhà Sáng Lập NIKE,Gã Nghiện Giày - Tự Truyện Của Nhà Sáng Lập NI...,112000,48000,8692.0,30,646,available
798,46789754,1466468282164,Hiểu Hết Về Kinh Doanh,Một trong những cuốn cẩm nang về Kinh doanh dễ...,273000,107000,5554.0,28,776,available
799,182972777,9391090895295,Rồng Đỏ,Những vụ giết người khủng khiếp vào những đêm ...,104000,31000,259.0,23,56,available

In [34]:
df.head()

,id,sku,name,short_description,price,discount,all_time_quantity_sold,discount_rate,review_count,inventory_status
0,74021317,5977911599303,Cây Cam Ngọt Của Tôi,“Vị chua chát của cái nghèo hòa trộn với vị ng...,79100,28900,60433.0,27,12218,available
1,184466860,6027901073690,Hành Tinh Của Một Kẻ Nghĩ Nhiều,"“Đó là mùa hè năm 2020, mùa hè của COVID-19 và...",59500,26500,13281.0,31,1355,available
2,189643105,7150413107642,Không Phải Sói Nhưng Cũng Đừng Là Cừu -Tặng kè...,SÓI VÀ CỪU - BẠN KHÔNG TỐT NHƯ BẠN NGHĨ ĐÂU! L...,88500,39500,8716.0,31,1054,available
3,207841114,1646492661143,Ghi Chép Pháp Y – Những Cái Chết Bí Ẩn,GHI CHÉP PHÁP Y - NHỮNG CÁI CHẾT BÍ ẨN – Làm c...,105000,45000,3002.0,30,425,available
4,106863963,7417324116157,Tâm Lý Học - Phác Họa Chân Dung Kẻ Phạm Tội,TÂM LÝ HỌC TỘI PHẠM - PHÁC HỌA CHÂN DUNG KẺ PH...,101000,44000,20181.0,30,5916,available

In [35]:
df.describe()

,id,sku,price,discount,all_time_quantity_sold,discount_rate,review_count
count,8.000000e+02,8.000000e+02,8.000000e+02,800.000000,782.000000,800.000000,800.000000
mean,1.346673e+08,5.386147e+12,1.200400e+05,40833.021250,4682.173913,24.793750,560.746250
std,7.007455e+07,2.595850e+12,1.112273e+05,40463.856681,26933.151582,13.108528,1089.101415
min,3.784480e+05,1.004950e+12,2.800000e+03,0.000000,1.000000,0.000000,0.000000
25%,7.432340e+07,3.091892e+12,6.172500e+04,15900.000000,430.250000,17.000000,57.000000
50%,1.597763e+08,5.311665e+12,9.375000e+04,33650.000000,1233.500000,26.000000,169.500000
75%,1.976343e+08,7.530399e+12,1.365000e+05,54000.000000,3364.750000,32.000000,574.250000
max,2.174192e+08,9.986522e+12,1.180000e+06,448000.000000,725392.000000,65.000000,12218.000000

1. Quyển sách nào bán chạy nhất.

In [36]:
book= df.loc[df.all_time_quantity_sold == df['all_time_quantity_sold'].max(), ["name", "price"]]
book

                                                  name   price
118  Sách OSHO Yêu - Being In Love - Yêu Trong Tỉnh...  117000

2. Top 10 quyển sách bán chạy nhất và tổng danh thu

In [39]:
feature =df[['name','all_time_quantity_sold', 'price']]
rsl2= feature.groupby('name').sum().sort_values('all_time_quantity_sold', ascending= False)
rsl2[:10]

,all_time_quantity_sold,price
name,,
Sách OSHO Yêu - Being In Love - Yêu Trong Tỉnh Thức,725392.0,117000
Cây Cam Ngọt Của Tôi,120866.0,158200
Tập Học Sinh Tiki Lan Tỏa Niềm Vui 96 Trang (Lốc 10 Cuốn) - Mẫu Ngẫu Nhiên,72634.0,51000
"Nóng Giận Là Bản Năng , Tĩnh Lặng Là Bản Lĩnh",67730.0,61800
Khi Hơi Thở Hóa Thinh Không,60065.0,62500
Điều Kỳ Diệu Của Tiệm Tạp Hóa NAMIYA (Tái Bản),55800.0,141800
Đàn Ông Sao Hỏa Đàn Bà Sao Kim,49675.0,124000
Dám Bị Ghét,47137.0,66700
Bước Chậm Lại Giữa Thế Gian Vội Vã (Tái Bản),45759.0,59100
Máy Tính Khoa Học Casio FX-580VN X,35635.0,670000

In [40]:
total_revenue = sum(rsl2[:10]['all_time_quantity_sold'] * rsl2[:10]['price'])
total_revenue

159431960500.0

3. Top 10 quyển sách được giảm giá nhiều nhất. Cho biết giá niêm yết của nó.

In [44]:
feature = df[['name', 'discount', 'price']]
feature['Listed price'] = feature['discount'] + feature['price']
rsl3= feature.sort_values('discount',ascending=False)[:10]
rsl3

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13880\968789354.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feature['Listed price'] = feature['discount'] + feature['price']

,name,discount,price,Listed price
307,Trọn Bộ 6 Tập: Tru Tiên (Tái Bản),448000,332000,780000
777,Combo 5 cuốn: Cơ Thể Tự Chữa Lành,356600,566400,923000
483,Harry Potter và Hội Phượng Hoàng - Bản Màu Bìa...,320000,1180000,1500000
761,Truyện Cổ Grimm (Ấn Bản Đầy Đủ Nhất Kèm 184 Mi...,255000,425000,680000
398,Miền Đất Hứa - Barack Obama (Bìa Cứng),231000,537000,768000
356,Sự Trỗi Dậy Và Suy Tàn Của Các Cường Quốc ( Tá...,221600,345400,567000
428,1000 Phát Minh Và Khám Phá Vĩ Đại,208400,290600,499000
318,Combo 4 Cuốn Bộ Sách: Nuôi Con Không Phải Là C...,195000,281000,476000
363,Tam Quốc Diễn Nghĩa - 2 Tập (Bìa Cứng - Tái Bả...,183700,206300,390000
374,Combo sách Giải mã 990+ tổng ôn bài thi ĐGNL Đ...,180000,320000,500000